version: '3.7'

services:
  dggsapi:
    build: .
    ports: 
      - "8080:3000"
  caddy:
    image: abiosoft/caddy
    ports:
      - 443:2015
    environment:
      - ACME_AGREE=true
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./certs:/etc/ssl
    links:
      - api
    restart: always
